// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsHih5sjeoQKgmsYQz8cXnepVqcNr-iQA',
    appId: '1:933246847412:web:3f0e7e2ac24c0b42450ae1',
    messagingSenderId: '933246847412',
    projectId: 'erp-app-7f98b',
    authDomain: 'erp-app-7f98b.firebaseapp.com',
    storageBucket: 'erp-app-7f98b.firebasestorage.app',
    measurementId: 'G-HX2Q21SMPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw3xUhZ-GV5kpLVks3hiEYykBJhPfo7O0',
    appId: '1:933246847412:android:e78a22edebeb40b8450ae1',
    messagingSenderId: '933246847412',
    projectId: 'erp-app-7f98b',
    storageBucket: 'erp-app-7f98b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhG1rJCWNXRvTBQ2sMRYUAe_IrWlB0288',
    appId: '1:933246847412:ios:73f98cc886aae094450ae1',
    messagingSenderId: '933246847412',
    projectId: 'erp-app-7f98b',
    storageBucket: 'erp-app-7f98b.firebasestorage.app',
    iosBundleId: 'com.example.erpMobileappUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhG1rJCWNXRvTBQ2sMRYUAe_IrWlB0288',
    appId: '1:933246847412:ios:73f98cc886aae094450ae1',
    messagingSenderId: '933246847412',
    projectId: 'erp-app-7f98b',
    storageBucket: 'erp-app-7f98b.firebasestorage.app',
    iosBundleId: 'com.example.erpMobileappUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsHih5sjeoQKgmsYQz8cXnepVqcNr-iQA',
    appId: '1:933246847412:web:2230fac9acace004450ae1',
    messagingSenderId: '933246847412',
    projectId: 'erp-app-7f98b',
    authDomain: 'erp-app-7f98b.firebaseapp.com',
    storageBucket: 'erp-app-7f98b.firebasestorage.app',
    measurementId: 'G-FX44Q1LF7R',
  );
}
